version: "3.8"
services:

  django:
    build: ./app
    container_name: django_container
    command: [ "./entrypoint.sh" ]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:6.0.16
    container_name: redis_container
    restart: always

  celery:
    build: ./app
    container_name: celery_container
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/code
    env_file:
      - .env
    depends_on:
      - django
      - redis

volumes:
  postgres-data: