version: "3.8"

services:
  app:
    container_name: django
    restart: always
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - static-data:/vol/web
    env_file:
      - .env

  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:6.0.16
    container_name: redis
    restart: always

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/app

volumes:
  static-data: