version: "3.8"
services:

  django:
    build: ./app
    container_name: django_container
    command: [ "./entrypoint.sh" ]
    restart: always
    volumes:
      - .:/code
#    ports:
#      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - outer_net
      - inner_net

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - inner_net

  redis:
    image: redis:6.0.16
    container_name: redis_container
    restart: always
    networks:
      - outer_net

  celery:
    build: ./app
    container_name: celery_container
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/code
    env_file:
      - .env
    networks:
      - outer_net
    depends_on:
      - django
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    volumes:
      - ./app/config/nginx:/etc/nginx/conf.d
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - django

networks:
  inner_net:
    name: inner_net
    driver: bridge
  outer_net:
    name: outer_net
    driver: bridge