version: "3.8"

services:
  django:
    container_name: django
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env