version: "3.8"
services:

  django:
    build: .
    container_name: django_container
    command: [ "./entrypoint.sh" ]
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - outer_net
      - inner_net

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - inner_net

  redis:
    image: redis:6.0.16
    container_name: redis_container
    restart: always
    networks:
      - outer_net

  celery:
    build: .
    container_name: celery_container
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/usr/src/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    networks:
      - outer_net
    depends_on:
      - django
      - redis

# Именные тома
volumes:
  data:

networks:
  inner_net:
    name: inner_net
    driver: bridge
  outer_net:
    name: outer_net
    driver: bridge