version: "3.8"
services:

  django:
    build: .
    container_name: django_container
    command: [ "./entrypoint.sh" ]
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - outer_net
      - inner_net

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - inner_net

  redis:
    image: redis:6.0.16
    container_name: redis_container
    restart: always
    networks:
      - outer_net

  celery:
    build: .
    container_name: celery_container
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - outer_net
    depends_on:
      - django
      - redis

networks:
  inner_net:
    name: inner_net
    driver: bridge
  outer_net:
    name: outer_net
    driver: bridge