version: "3.9"

services:
  app:
    container_name: django
    build:
      context: .
    restart: always
    volumes:
      - ./app:/app
      - static-data:/vol/web
    env_file:
      - .env

  proxy:
    container_name: nginx
    restart: always
    build:
      context: ./proxy
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
    depends_on:
      - app

  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6.0.16
    container_name: redis
    restart: always

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis

volumes:
  static-data: