version: "3.8"

services:
  django:
    container_name: django
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:6.0.16
    container_name: redis
    restart: always

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A config worker -l INFO
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

volumes:
  postgres-data: